---
- name: add storage for kodi
  become: yes
  command: "lxc config device add {{ inventory_hostname }} dlna disk source={{ src_path }} path={{ kodi_path }}"
  delegate_to: localhost
  failed_when: no

